### PR TITLE
 Added a CONTRIBUTING.md file to the Tourism Website

### PR DESCRIPTION
**Pull request by Techkrish1**
I created a contributing.md file which is assigned to me to implement.
issue no #31 
Please review it.

### CODE REVIEW

**Comment by Techkrish1** [comment]
what can I do?
https://www.awesomescreenshot.com/image/31513544?key=4c7908896d6ec752039f412c1f43df9b

**Comment by PritamSarbajna** [comment]
> what can I do? https://www.awesomescreenshot.com/image/31513544?key=4c7908896d6ec752039f412c1f43df9b

Nothing to worry about it

**Comment by Techkrish1** [comment]
can you merge it

**Review by PritamSarbajna — APPROVED** [review]
This is nice @Techkrish1

**Comment by PritamSarbajna** [comment]
Just let me make some changes to it

**Comment by Techkrish1** [comment]
Thank you. I want to contribute to you more.

**Comment by PritamSarbajna** [comment]
Yeah sure keep checking the issues

**Comment by Techkrish1** [comment]
should I delete my branch?
image

**Comment by PritamSarbajna** [comment]
@Techkrish1 yeah it won't cause any problem

**Pull request merged**
