### PR TITLE
Added several glass/tranparent navbar effect

### PR DESCRIPTION
**Pull request by hassana123**
added  three different transparent navbar effect, choose the one that is most suitable

### CODE REVIEW

**Comment by PritamSarbajna** [comment]
Hey @hassana123 can you make this boxes go away ?? or do I have to tell you which code you should remove ?

imageedit_2_2299725813

**Comment by hassana123** [comment]
on it

**Comment by PritamSarbajna** [comment]
Hey @hassana123 can you make it more like this ?

Screenshot (196)

**Don't change the color. Instead use this piece of code**

```
.navbar {
  position: fixed;
  top: 0;
  background: rgba(0,0,0,0.3);
  backdrop-filter: saturate(180%) blur(10px);
  left: 0;
  display: flex;
  width: 100%;
  justify-content: space-between;
  padding: 10px;
  z-index: 10;
  color: whitesmoke;
}
```

**Comment by hassana123** [comment]
done

**Comment by PritamSarbajna** [comment]
Thank you @hassana123 🙌
make sure to check other [issues](https://github.com/PritamSarbajna/tourism-website/issues)

**Comment by hassana123** [comment]
Sure

**Pull request merged**
