### PR TITLE
Contribution UI

### PR DESCRIPTION
**Pull request by abitsalihu**
Added myself as a contributor in the HTML file.
Changed the User Interface of "Contributor cards" when a user hovers over it!
Screen Shot 2022-09-03 at 17 23 29

If there is anything wrong with the pull request or anything in particular please tell me, as this is the first time I am contributing to someone else code!

### CODE REVIEW

**Review by PritamSarbajna — CHANGES_REQUESTED** [review]
Hey @abitsalihu when I'm hovering one single contributor card every contributor cards are moving also they are little bit shaking when hovering can you please fix that ??

> NOTE : Only resolve the issue that is assigned to you. Don't change any code that is unrelated to the issue.

**Comment by abitsalihu** [comment]
I fixed the issue with the other stuff moving when hovering over one, but I cant see the shaking?
If you could please guide me how do i push the fix I just made, do I make another request do I push it into my fork or do I push it directly to head?

**Comment by PritamSarbajna** [comment]
Hey @abitsalihu you can checkout the PR and make changes to it as well as editing the file you just committed.

> NOTE : You can see `code<>` on the top right corner beneath the star option for checking out the PR

**Comment by abitsalihu** [comment]
Hey, I just pushed my commit with the fix on to my fork which is now in the pull request, is everything good now?

**Comment by abitsalihu** [comment]
Hey @PritamSarbajna  I just pushed the fix to my fork which is in this pull request, Is everything okay now?

**Comment by PritamSarbajna** [comment]
Thanks @abitsalihu really appreciate it 🙌

**Pull request merged**
