### PR TITLE
Created a Contributors Section

### PR DESCRIPTION
**Pull request by prakhartiwari2507**
Hello @PritamSarbajna,
I have created a basic version of the contributors' section, I don't expect it to be perfect, so please tell me what changes should be made. Thank you.

https://user-images.githubusercontent.com/65062036/185745731-4aa32722-f604-4f24-a157-dc25043e2152.mp4

### CODE REVIEW

**Comment by PritamSarbajna** [comment]
Hey @prakhartiwari2507 your PR has merge conflicts also do change the background of the contributor section

**Review by PritamSarbajna — CHANGES_REQUESTED** [review]
Change background

**Comment by prakhartiwari2507** [comment]
Hey, what background should I set there? a plain white? Wouldn't that make the cards invisible? So should I give them a border or box shadow? Please tell briefly.

> Change background

**Comment by PritamSarbajna** [comment]
> Hey, what background should I set there? a plain white? Wouldn't that make the cards invisible? So should I give them a border or box shadow? Please tell briefly.
> 

Hey @prakhartiwari2507 please update your repo first then you can decide

**Comment by prakhartiwari2507** [comment]
Hey @PritamSarbajna Please be my mentor here, I am actually confused about this situation. What is merge conflict I know the basics, but how to solve it, and what really has happened, I am not aware. Kindly help me out.

**Comment by PritamSarbajna** [comment]
> Hey @PritamSarbajna Please be my mentor here, I am actually confused about this situation. What is merge conflict I know the basics, but how to solve it, and what really has happened, I am not aware. Kindly help me out.

Yeah sure @prakhartiwari2507 just go through this [tutorial](https://youtu.be/deEYHVpE1c8) . After this if you still not able to fix then please let me know.

**Pull request closed without merging**
