### PR TITLE
Change fonts

### PR DESCRIPTION
**Pull request by mamba-dev-KE**
Hey there, came across the project and decided to handle the fonts. This is a summary of the changes I've made: 

- Adding the font-families as css variables so that they can easily be changed on one place and reflect throughout the whole app. 
- UI updates like adding a container to ensure on big screens size is capped. 
- Added some responsive fonts
- Adjusted the positioning of some things into a more consistent pattern.

Looking forward to the code review!

### CODE REVIEW

**Comment by PritamSarbajna** [comment]
Hey @mamba-dev-KE you have added a blurred container in the hero section please remove that

**Comment by mamba-dev-KE** [comment]
I added 2, do I remove the other one too? Thanks

**Comment by PritamSarbajna** [comment]
@mamba-dev-KE hi after your changing the codde it's now looking like this can you fix it ?

**Comment by mamba-dev-KE** [comment]
@PritamSarbajna did you attach a photo or something?

**Comment by PritamSarbajna** [comment]
@mamba-dev-KE you can see here 

Screenshot (207)

**Comment by mamba-dev-KE** [comment]
Screenshot from 2022-08-17 21-05-50 This is how it displays for me, but I will investigate @PritamSarbajna

**Comment by PritamSarbajna** [comment]
Hey @mamba-dev-KE it should look like 2 * 2 box. Also resolve the merge conflicts

**Review by PritamSarbajna — CHANGES_REQUESTED** [review]
Hey @mamba-dev-KE it should look like 2 * 2 box. Also resolve the merge conflicts

**Comment by mamba-dev-KE** [comment]
Hey @PritamSarbajna. Let me work on it

**Comment by PritamSarbajna** [comment]
> Hey @PritamSarbajna. Let me work on it

yeah sure @mamba-dev-KE

**Comment by mamba-dev-KE** [comment]
Hey @PritamSarbajna you can have a look

**Review by PritamSarbajna — APPROVED** [review]
this code looks good... Thank you 🙌

**Pull request merged**
