### PR TITLE
Contributors section

### PR DESCRIPTION
**Pull request by prakhartiwari2507**
Kindly Check if this needs any more changes @PritamSarbajna 

https://user-images.githubusercontent.com/65062036/186525151-92cfa2ef-1ac5-452a-8b88-790a9c19a6f6.mp4

### CODE REVIEW

**Review by PritamSarbajna — CHANGES_REQUESTED** [review]
Hey don't make changes in upcoming events section

**Comment by prakhartiwari2507** [comment]
Yes @PritamSarbajna I haven't touched anything else except the Contributions section HTML and CSS code.

**Comment by prakhartiwari2507** [comment]
Oh sorry I didn't saw the changed section, I need to look where it is messing up

**Comment by PritamSarbajna** [comment]
> Oh sorry I didn't saw the changed section, I need to look where it is messing up

Yeah @prakhartiwari2507 just change that and make the contributors section's bg as black (#000)

**Comment by prakhartiwari2507** [comment]
> > Oh sorry I didn't saw the changed section, I need to look where it is messing up
> 
> Yeah @prakhartiwari2507 just change that and make the contributors section's bg as black (#000)

Hey @PritamSarbajna Kindly check now if everything is fine.

**Review by PritamSarbajna — APPROVED** [review]
Thanks @prakhartiwari2507 🙌

I am creating another issue to make the contributor section look better or you can raise this issue too.

**Comment by prakhartiwari2507** [comment]
Yes @PritamSarbajna you create it according to the needs of this website.

**Pull request merged**
