### PR TITLE
Foxcoder508 fix

### PR DESCRIPTION
**Pull request by Brainiac-M**
I have changed the logo to a nicer-looking one.

### CODE REVIEW

**Comment by PritamSarbajna** [comment]
Hey @Brainiac-M can you make it a little bit small

**Comment by Brainiac-M** [comment]
Alright. I will do that

**Comment by Brainiac-M** [comment]
Done. I think it looks nicer now. I like the dark mode too. Nice work

**Comment by PritamSarbajna** [comment]
> Done. I think it looks nicer now. I like the dark mode too. Nice work

Don't you think it's too wide ??

**Comment by Brainiac-M** [comment]
Done. Is it cool this way?

**Review by PritamSarbajna — APPROVED** [review]
this is better. Thanks @Brainiac-M 🙌

**Pull request merged**
