### PR TITLE
fixed the icons issue

### PR DESCRIPTION
**Pull request by Brainiac-M**
I have fixed the icons issue in the contact section. Now you can hover on the each box and it will behave normally.

### CODE REVIEW

**Comment by PritamSarbajna** [comment]
Hey @Brainiac-M can you please update your forked repo

**Comment by Brainiac-M** [comment]
Hi @PritamSarbajna, I think my branch is up to date now.

**Review by PritamSarbajna — APPROVED** [review]
Thanks @Brainiac-M 🙌

**Comment by Brainiac-M** [comment]
You're welcome.

**Pull request merged**
