### PR TITLE
Rosplab

### PR DESCRIPTION
**Pull request by sayalihere**
#64 done changes with the texts
#62 i have done a minor change in this .please review this .  
Proposing new feature: 
In my opinion the text is looking much better than if the logo was added because the website is in more sophisticated way so the text looks better .

### CODE REVIEW

**Comment by sayalihere** [comment]
done

**Review by PritamSarbajna — CHANGES_REQUESTED** [review]
Just change the design of the logo don't change the inner text. Let it be **"ADVENTURE"**

**Comment by sayalihere** [comment]
@PritamSarbajna  hello, i have the asked changes , can you review it ? let me know : ))

**Review by PritamSarbajna — APPROVED** [review]
This code looks good !!

**Comment by sayalihere** [comment]
@PritamSarbajna  thankyou 😊.

**Pull request merged**
