### PR TITLE
Welcome image banner and dark theme implemented

### PR DESCRIPTION
**Pull request by Iamslok**
Main welcome banner and dark theme implemented

### CODE REVIEW

**Comment by PritamSarbajna** [comment]
Hey @Iamslok your merge have conflicts. If you don't know how to resolve then just ask

**Comment by Iamslok** [comment]
@PritamSarbajna can you help me to resolve the conflicts in visual studio code

**Comment by PritamSarbajna** [comment]
> @PritamSarbajna can you help me to resolve the conflicts in visual studio code

Hey @Iamslok you don't have to go to vs code. Just go to your repo and fetch the main repo from their and then do a git pull
you can refer to this [tutorial](https://www.youtube.com/watch?v=deEYHVpE1c8&t=404s)

**Review by PritamSarbajna — APPROVED** [review]
This code looks good. Thank you 🙌

**Comment by Iamslok** [comment]
@PritamSarbajna I'm not on the contributor's list

**Comment by PritamSarbajna** [comment]
@Iamslok you will be github takes some time to update

**Pull request merged**
